api:
  root: https://api.openweathermap.org/data/2.5

swagger:
  host:
    url: localhost:8080
    path:

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.11.11